.build_script_template : &build_script_definition
  script:
    - mkdir -p ~/ros_ws/src
    - cd ~/ros_ws
    - catkin_make
    - cd src
    - cp -r /builds/$GITLAB_USER_LOGIN/ontologenius .
    - cd ..
    - catkin_make

.test_script_template : &test_script_definition_py2
  script:
    - mkdir -p ~/ros_ws/src
    - cd ~/ros_ws
    - catkin_make
    - cd src
    - cp -r /builds/$GITLAB_USER_LOGIN/ontologenius .
    - cd ..
    - pip install requests --user
    - source devel/setup.bash
    - catkin_make
    - source devel/setup.bash
    - catkin_make run_tests_ontologenius_rostest -j1 && catkin_make test -j1

.test_script_template : &test_script_definition_py3
  script:
    - mkdir -p ~/ros_ws/src
    - cd ~/ros_ws
    - catkin_make
    - cd src
    - cp -r /builds/$GITLAB_USER_LOGIN/ontologenius .
    - cd ..
    - pip3 install requests --user
    - source devel/setup.bash
    - catkin_make
    - source devel/setup.bash
    - catkin_make run_tests_ontologenius_rostest -j1 && catkin_make test -j1

.kinetic_before_template : &kinetic_before_definition
  before_script:
  - source /opt/ros/kinetic/setup.bash
  - apt-get update -qq && apt-get install -y libcppunit-1.13-0v5 libcppunit-dev python-rosdep

.lunar_before_template : &lunar_before_definition
  before_script:
  - source /opt/ros/lunar/setup.bash
  - apt-get update -qq && apt-get install -y libcppunit-1.13-0v5 libcppunit-dev libtinyxml-dev python-rosdep

.melodic_before_template : &melodic_before_definition
  before_script:
  - source /opt/ros/melodic/setup.bash
  - apt-get update -qq && apt-get install -y libcppunit-1.14-0 libcppunit-dev libtinyxml-dev python-rosdep

.noetic_before_template : &noetic_before_definition
  before_script:
  - source /opt/ros/noetic/setup.bash
  - apt-get update -qq && apt-get install -y libcppunit-1.15-0 libcppunit-dev libtinyxml-dev git-all python3-rosdep


stages:
  - build
  - test

run-build-kinetic:
  image: ros:kinetic-perception-xenial
  stage: build
  <<: *kinetic_before_definition
  <<: *build_script_definition

run-test-kinetic:
  stage: test
  image: ros:kinetic-perception-xenial
  <<: *kinetic_before_definition
  <<: *test_script_definition_py2

run-build-lunar:
  image: ros:lunar-perception-xenial
  stage: build
  allow_failure : true
  <<: *lunar_before_definition
  <<: *build_script_definition

run-test-melodic:
  stage: test
  image: ros:melodic-perception-bionic
  <<: *melodic_before_definition
  <<: *test_script_definition_py2

run-build-melodic:
  image: ros:melodic-perception-bionic
  stage: build
  <<: *melodic_before_definition
  <<: *build_script_definition

run-test-noetic:
  stage: test
  image: ros:noetic-perception-focal
  <<: *noetic_before_definition
  <<: *test_script_definition_py3

run-build-noetic:
  image: ros:noetic-perception-focal
  stage: build
  <<: *noetic_before_definition
  <<: *build_script_definition
