#include "ontologenius/core/ontologyIO/Owl/OntologyOwlWriter.h"

#include <cstdio>
#include <iostream>
#include <string>

#include "ontologenius/core/ontoGraphs/Graphs/OntologyGraphs.h"
#include "ontologenius/core/ontoGraphs/Ontology.h"
#include "ontologenius/core/ontologyIO/Owl/writers/AnnotationOwlWriter.h"
#include "ontologenius/core/ontologyIO/Owl/writers/ClassOwlWriter.h"
#include "ontologenius/core/ontologyIO/Owl/writers/DataPropertiesOwlWriter.h"
#include "ontologenius/core/ontologyIO/Owl/writers/IndividualOwlWriter.h"
#include "ontologenius/core/ontologyIO/Owl/writers/ObjectPropertiesOwlWriter.h"
#include "ontologenius/core/ontologyIO/Owl/writers/RuleOwlWriter.h"
#include "ontologenius/graphical/Display.h"

namespace ontologenius {

  OntologyOwlWriter::OntologyOwlWriter(OntologyGraphs* graphs) : graphs_(graphs),
                                                                 file_(nullptr)
  {}

  void OntologyOwlWriter::write(const std::string& file_name)
  {
    if(file_name != "none")
      file_name_ = file_name;

    if(file_name_ == "none")
      return;

    file_ = fopen(file_name_.c_str(), "w");
    if(file_ == nullptr)
    {
      Display::error("Fail to open file : ", false);
      std::cout << file_name_ << std::endl;
      return;
    }

    ns_ = "urn:absolute:ontologenius";

    writeStart();

    writeBanner("Annotations Properties");
    AnnotationOwlWriter annotations(&graphs_->object_properties_, &graphs_->data_properties_, file_, ns_);
    annotations.write();

    writeBanner("Classes");
    ClassOwlWriter classes(&graphs_->classes_, file_, ns_);
    classes.write();

    writeBanner("Object Properties");
    ObjectPropertiesOwlWriter object_properties(&graphs_->object_properties_, file_, ns_);
    object_properties.write();

    writeBanner("Data properties");
    DataPropertiesOwlWriter data_properties(&graphs_->data_properties_, file_, ns_);
    data_properties.write();

    writeBanner("Individuals");
    IndividualOwlWriter individuals(&graphs_->individuals_, file_, ns_);
    individuals.write();

    writeBanner("General axioms");
    classes.writeGeneralAxioms();
    individuals.writeGeneralAxioms();

    writeBanner("Rules");
    RuleOwlWriter rules(&graphs_->rules_, file_, ns_);
    rules.write();

    writeEnd();

    Display::success("ontology loaded in : ", false);
    std::cout << file_name_ << std::endl;

    if(file_ != nullptr)
      fclose(file_);
  }

  void OntologyOwlWriter::writeStart()
  {
    const std::string tmp = "<?xml version=\"1.0\"?> \n\
<rdf:RDF xmlns=\"" + ns_ +
                            "#\" \n\
     xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n\
     xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n\
     xmlns:xml=\"http://www.w3.org/XML/1998/namespace\"\n\
     xmlns:xsd=\"http://www.w3.org/2001/XMLSchema#\"\n\
     xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\"\n\
     xmlns:swrl=\"http://www.w3.org/2003/11/swrl#\"\n\
     xmlns:swrlb=\"http://www.w3.org/2003/11/swrlb#\"\n\
     xmlns:onto=\"" + ns_ + "#\">\n\
    <owl:Ontology rdf:about=\"" +
                            ns_ + "\"/>\n\n\n\n";
    writeString(tmp);
  }

  void OntologyOwlWriter::writeEnd()
  {
    const std::string tmp = "</rdf:RDF> \n\n\n\n\
<!-- Generated by the ontologenius https://sarthou.github.io/ontologenius/ -->\n";
    writeString(tmp);
  }

  void OntologyOwlWriter::writeBanner(const std::string& name)
  {
    const std::string tmp = "    <!--\n\
    ///////////////////////////////////////////////////////////////////////////////////////\n\
    //\n\
    // " + name + "\n\
    //\n\
    ///////////////////////////////////////////////////////////////////////////////////////\n\
     -->\n\n\n\n\n";
    writeString(tmp);
  }

  void OntologyOwlWriter::writeString(const std::string& text)
  {
    if(file_ != nullptr)
      fwrite(text.c_str(), sizeof(char), text.size(), file_);
  }

} // namespace ontologenius
