flow:
  - ReasonerChain
  - ReasonerGeneralize
  - ReasonerDictionary
  - ReasonerInverseOf
  - ReasonerRangeDomain
  - ReasonerSymetric
ReasonerGeneralize:
  min_count : 2
  min_percent : 0.7
ReasonerDictionary:
  use_id : true
