name: ROS2 CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        include:
          - operating-system: ubuntu-22.04
            ros_distro: humble
            disto: jammy
          - operating-system: ubuntu-22.04
            ros_distro: iron
            disto: jammy
    env:
      ROS_CI_DESKTOP: ${{ matrix.disto }}
      CI_SOURCE_PATH: $(pwd)
      ROS_DISTRO: ${{ matrix.ros_distro }}
    steps:
      - name: Setup ROS
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros_distro }}

      - name: Install deps
        run: |
            sudo apt install dpkg
            sudo apt install -y qtbase5-dev qtdeclarative5-dev
            sudo apt install -y libcppunit-dev libcurl4-openssl-dev
            sudo apt-get install python3-rosdep
            source /opt/ros/$ROS_DISTRO/setup.bash

      - name: build
        run: |
          source /opt/ros/$ROS_DISTRO/setup.bash
          cmake --version
          mkdir -p ~/ros2_ws/src
          cd ~/ros2_ws
          colcon build --symlink-install
          source install/setup.bash
          export ROS_LOCALHOST_ONLY=1
          cd ~/ros2_ws/src
          ln -s ~/work  # $CI_SOURCE_PATH
          cd ..
          colcon build --symlink-install